# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-13 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
                ('travel_date_from', models.DateField(blank=True, null=True)),
                ('travel_date_to', models.DateField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_trips', to='login.User')),
                ('joined_by', models.ManyToManyField(related_name='joined', to='login.User')),
            ],
        ),
    ]
